### PR TITLE
 Some rename & Fix import resolution

### PR DESCRIPTION
**Pull request by Butter934**
1. Rename some method
2. Fix incorrect import path resolution #11

### CODE REVIEW

**Comment by thisrabbit** [comment]
Since I am not familiar with ENRE-py, I can only propose some questions:

1. It seems this fix had some adjustments on the path handling system, so after the fix, ENRE will not be interrupted by unhandled error?

1. After the fix, what will ENRE do when meeting a wildcard import statement `from xxx import *` that NOT IN the module level? Print error and omit this line or still try to bind dependencies?

**Comment by Butter934** [comment]
The unhandled error mentioned in original issue is caused by incorrect import path resolution rather than syntax error. 
`Local import` (namely import or using wildcard) feature should work as expected already. 
Here is a test case with analyze result:
```py
# python_feature/foo.py
def foo():
    ...
```


```py
# python_feature/bar.py
class Bar:
    from foo import *
    def bar(self):
        foo()  # Understand establishes a dependency of bar -call->foo, however this code is invalid and cannot really be executed

```

```js
{
    "variables": [
        {
            "id": 1,
            "qualifiedName": "python_feature.bar",
            "category": "Module",
            "location": {
                "startLine": -1,
                "endLine": -1,
                "startColumn": -1,
                "endColumn": -1
            },
            "File": "python_feature/bar.py"
        },
        {
            "id": 4,
            "qualifiedName": "python_feature.bar.Bar",
            "category": "Class",
            "location": {
                "startLine": 2,
                "endLine": -1,
                "startColumn": 6,
                "endColumn": -1
            },
            "File": "python_feature/bar.py"
        },
        {
            "id": 6,
            "qualifiedName": "python_feature.bar.Bar.bar",
            "category": "Function",
            "location": {
                "startLine": 4,
                "endLine": -1,
                "startColumn": 8,
                "endColumn": -1
            },
            "File": "python_feature/bar.py"
        },
        {
            "id": 7,
            "qualifiedName": "python_feature.bar.Bar.bar.self",
            "category": "Parameter",
            "location": {
                "startLine": 4,
                "endLine": 4,
                "startColumn": 12,
                "endColumn": 16
            },
            "File": "python_feature/bar.py"
        },
        {
            "id": 8,
            "qualifiedName": "foo",
            "category": "Unknown Variable",
            "location": {
                "startLine": -1,
                "endLine": -1,
                "startColumn": -1,
                "endColumn": -1
            }
        },
        {
            "id": 2,
            "qualifiedName": "python_feature.foo",
            "category": "Module",
            "location": {
                "startLine": -1,
                "endLine": -1,
                "startColumn": -1,
                "endColumn": -1
            },
            "File": "python_feature/foo.py"
        },
        {
            "id": 5,
            "qualifiedName": "python_feature.foo.foo",
            "category": "Function",
            "location": {
                "startLine": 1,
                "endLine": -1,
                "startColumn": 4,
                "endColumn": -1
            },
            "File": "python_feature/foo.py"
        },
        {
            "id": 3,
            "qualifiedName": "python_feature",
            "category": "Package",
            "location": {
                "startLine": -1,
                "endLine": -1,
                "startColumn": -1,
                "endColumn": -1
            },
            "File": "python_feature"
        }
    ],
    "cells": [
        {
            "src": 1,
            "dest": 4,
            "values": {
                "kind": "Define",
                "in_type_context": false
            },
            "location": {
                "startLine": 2,
                "startCol": 0
            }
        },
        {
            "src": 4,
            "dest": 5,
            "values": {
                "kind": "Import",
                "in_type_context": false
            },
            "location": {
                "startLine": 3,
                "startCol": 4
            }
        },
        {
            "src": 4,
            "dest": 6,
            "values": {
                "kind": "Define",
                "in_type_context": false
            },
            "location": {
                "startLine": 4,
                "startCol": 8
            }
        },
        {
            "src": 6,
            "dest": 7,
            "values": {
                "kind": "Define",
                "in_type_context": false
            },
            "location": {
                "startLine": 4,
                "startCol": 12
            }
        },
        {
            "src": 6,
            "dest": 8,
            "values": {
                "kind": "Call",
                "in_type_context": false
            },
            "location": {
                "startLine": 5,
                "startCol": 8
            }
        },
        {
            "src": 2,
            "dest": 5,
            "values": {
                "kind": "Define",
                "in_type_context": false
            },
            "location": {
                "startLine": 1,
                "startCol": 4
            }
        },
        {
            "src": 3,
            "dest": 1,
            "values": {
                "kind": "Contain",
                "in_type_context": false
            },
            "location": {
                "startLine": 0,
                "startCol": 0
            }
        },
        {
            "src": 3,
            "dest": 2,
            "values": {
                "kind": "Contain",
                "in_type_context": false
            },
            "location": {
                "startLine": 0,
                "startCol": 0
            }
        }
    ]
}
```
The destination of calling `foo()` resolved as `unknown variable` is an expecting behavior, since import at class's body won't bring imported names to scope of its inner function.

**Comment by thisrabbit** [comment]
I am agreed with what the program currently outputs as you have shown, however, I am still confused with some details.

1. Could you please clarify `since import at class's body won't bring imported names to scope of its inner function`? Cause the following code actually works:

```py
class Bar:
    from playground import var, func, Clz

    def bar(self):
        self.func()
```

Or could you please show a result snippet of what fixed ENRE output on this code, especially does it extract a dependency `bar -call-> func`?

2. The wildcard import `from xxx import *` is NOT allowed if it is not in the top level scope as described in the [spec](https://docs.python.org/3/reference/simple_stmts.html#import#:~:text=The%20wild%20card%20form%20of%20import). Python official has no definition on what will happen if no error is thrown and the program continues executing. So after this fix, how would this wrong syntax affect ENRE's analysis? BTW, I recommend that we should establish a system that detects and hold syntax/semantic errors we found during the analysis.

**Comment by Butter934** [comment]
```pyt
class Bar:
    from playground import var, func, Clz

    def bar(self):
        self.func()
```
This snippet is different as the one of the original issue, it use a `self` to assess the class's attribute. It needs add imported entity to class's attribute, which is not supported yet.

> import at class's body won't bring imported names to scope of its inner function

 means the `foo` is not available at body of `bar`.
 
```py
# python_feature/bar.py
class Bar:
    from foo import *
    def bar(self):
        foo()  # Understand establishes a dependency of bar -call->foo, however this code is invalid and cannot really be executed
```

**Pull request merged**
